rootPageId: 1
base: /
baseVariants: {}
languages:
  -
    title: English
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.utf8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: global
errorHandling: {}
routes: {}
routeEnhancers:
  ExamplePlugin:
    type: Extbase
    extension: ExampleExtension
    plugin: Address
    defaultController: 'Address::index'
    routes:
      -
        routePath: '/edit/{address}'
        _controller: 'Address::edit'
        _arguments:
          'address': 'address'
      -
        routePath: '/update'
        _controller: 'Address::update'
    aspects:
      address:
        type: PersistedPatternMapper
        tableName: 'tx_exampleextension_domain_model_address'
        routeFieldPattern: '^(?P<company_name>.+)-(?P<uid>\d+)$'
        routeFieldResult: '{company_name}-{uid}'
